name: "🎯 오늘의 문제"
description: "오늘의 알고리즘 문제 템플릿"
body:
  - type: markdown
    attributes:
      value: "# 오늘의 문제"
  - type: input
    id: problem-title
    attributes:
      label: "문제 제목"
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: "플랫폼"
      options:
        - LeetCode
        - Baekjoon
        - Programmers
        - SWEA
    validations:
      required: true
