name: "🎯 오늘의 문제"
description: "오늘의 알고리즘 문제 템플릿"
labels: ["문제풀이"]
title: "[YYYY.MM.DD] 🎯 오늘의 문제"
body:
  - type: markdown
    attributes:
      value: |
        # 📌 제목 작성 가이드
        제목은 다음 형식으로 작성해주세요:
        `[YYYY.MM.DD] 🎯 오늘의 문제`
  - type: dropdown
    id: platform
    attributes:
      label: "## 플랫폼"
      options:
        - LeetCode
        - Baekjoon
        - Programmers
        - SWEA
    validations:
      required: true
  - type: input
    id: problem-title
    attributes:
      label: "## 문제 번호 - 제목"
      placeholder: "예) 250137 - 붕대 감기"
    validations:
      required: true
  - type: input
    id: problem-link
    attributes:
      label: "## 문제 링크"
      placeholder: "https://..."
    validations:
      required: true
  - type: input
    id: difficulty
    attributes:
      label: "## 난이도"
      placeholder: "예) Lv. 1"
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        # ⏰ 제출 기한
        > 오늘 23:00까지

        # ⚠️ 중요 안내
        > **Wiki 업데이트를 잊지 마세요!**
        
        1. Wiki의 "Weekly" 페이지에 아래 형식으로 추가해주세요:
        ~~~
        | 날짜       | 문제                      | 분류          |
        |:----------:|:-------------------------:|:-------------:|
        | YYYY.MM.DD | [문제명](문제링크)        | 알고리즘 유형 |
        ~~~
