name: "🎯 오늘의 문제"
description: "오늘의 알고리즘 문제 템플릿"
body:
  - type: input
    id: title
    attributes:
      label: "제목"
      placeholder: "[2025.02.07] 🎯 오늘의 문제"
      description: "날짜를 수정하여 작성해주세요"
    validations:
      required: true
  - type: markdown
    attributes:
      value: "# 🎯 오늘의 문제"
  - type: input
    id: problem-title
    attributes:
      label: "문제"
      placeholder: "예) 프로그래머스 250137 - 붕대 감기"
    validations:
      required: true
  - type: input
    id: problem-link
    attributes:
      label: "문제 링크"
    validations:
      required: true
  - type: input
    id: difficulty
    attributes:
      label: "난이도"
      placeholder: "예) Lv. 1"
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## ⏰ 제출 기한
        오늘 23:00까지
