name: Commit Message Check
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  check-commit-message:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Check LATEST Commit Message
        run: |
          latest_commit=$(git log -1 --pretty=format:"%s")
          
          if ! [[ $latest_commit =~ ^\[(Lv\.\s?[0-5]|(Bronze|Silver|Gold|Platinum)\s?(I|II|III|IV|V)|D\s?[1-8]|Easy|Medium|Hard)\].*$ ]]; then
            echo "::error::Latest commit '$latest_commit' is invalid"
            exit 1
          else
            echo "✓ Valid latest commit: $latest_commit"
          fi
          done <<< "$commits"
