name: Commit Message Check
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  check-commit-message:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Validate Commit Message
        run: |
          # UTF-8 환경 설정 추가
          export LC_ALL=C.UTF-8
          
          # 커밋 메시지 추출 (UTF-8 인코딩 명시)
          latest_commit=$(git log --no-merges --pretty=format:"%s" --encoding=UTF-8 origin/main..HEAD | head -n 1 | tr -d '\r')

          
          # 개선된 정규식 (유니코드 허용)
          regex='^\[(Lv\.\s?[0-5]|(Bronze|Silver|Gold|Platinum)\s?(I|II|III|IV|V)|D\s?[1-8]|Easy|Medium|Hard)\][[:print:][:space:]]*$'
          
          if ! [[ $latest_commit =~ $regex ]]; then
            echo "::error::Invalid commit: $latest_commit"
            exit 1
          fi
