name: Commit Message Check
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  check-commit-message:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Validate Commit Message
        run: |
          # UTF-8 환경 설정 추가
          export LC_ALL=C.UTF-8
          
          # 커밋 메시지 추출 (UTF-8 인코딩 명시)
          latest_commit=$(git log -1 --no-merges --pretty=format:"%s" --encoding=UTF-8 | tr -d '\r')
          
          # 개선된 정규식 (유니코드 허용)
          regex='^\[(Lv\.\s?[0-5]|(Bronze|Silver|Gold|Platinum)\s?(I|II|III|IV|V)|D\s?[1-8]|Easy|Medium|Hard)\][[:print:][:space:]]*$'
          
          if ! [[ $latest_commit =~ $regex ]]; then
            echo "::error::Invalid commit: $latest_commit"
            exit 1
          fi

- name: Validate New Commits
  run: |
    # main과 PR 브랜치 비교
    base_sha=${{ github.event.pull_request.base.sha }}
    head_sha=${{ github.event.pull_request.head.sha }}
    
    git log --no-merges --pretty=format:"%s" $base_sha..$head_sha | while read msg; do
      if ! [[ $msg =~ ^\[Lv\. ]]; then
        echo "::error::Invalid commit: $msg"
        exit 1
      fi
    done
