name: Commit Message Check
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  check-commit-message:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate Latest NON-MERGE Commit
        run: |
          latest_commit=$(git log -1 --no-merges --pretty=format:"%s")
          
          if [[ -z "$latest_commit" ]]; then
            echo "::error::No non-merge commits found"
            exit 1
          fi
          
          if ! [[ $latest_commit =~ ^\[(Lv\.\s?[0-5]|(Bronze|Silver|Gold|Platinum)\s?(I|II|III|IV|V)|D\s?[1-8]|Easy|Medium|Hard)\].*$ ]]; then
            echo "::error::Invalid commit: $latest_commit"
            exit 1
          else
            echo "✓ Valid commit: $latest_commit"
          fi
